services:
  nginx:
    container_name: nginx_app
    image: nuniesmith/nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      TZ: "America/New_York"
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped