services:
  # Nginx web server
  nginx:
    container_name: nginx_app
    image: ${DOCKER_REGISTRY:-local}/nginx:${TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
      args:
        SERVICE_NAME: ${SERVICE_NAME:-honeybun}
        SERVICE_PORT: ${SERVICE_PORT:-80}
        APP_VERSION: ${APP_VERSION:-1.0.0}
        APP_ENV: ${APP_ENV:-development}
        CONFIG_PATH: ${CONFIG_PATH:-./config/nginx}
        HTML_PATH: ${HTML_PATH:-./config/html}
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
    environment:
      TZ: ${TZ:-"America/New_York"}
      ENABLE_HEALTHCHECK: ${ENABLE_HEALTHCHECK:-"true"}
      ENABLE_GZIP: ${ENABLE_GZIP:-"false"}
      ENABLE_HTTPS_REDIRECT: ${ENABLE_HTTPS_REDIRECT:-"false"}
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - nginx_www_data:/var/www/html
      # Optional: mount SSL certificates
      - ${SSL_CERT_PATH:-./ssl}:/etc/nginx/ssl:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - honeybun-network
    # Add resource constraints
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  
networks:
  honeybun-network:
    driver: bridge


volumes:
  nginx_www_data:
    driver: local