services:
  nginx:
    container_name: nginx_app
    image: ${NGINX_IMAGE_TAG:-nginx_app:latest}
    build:
      context: .
      dockerfile: ${NGINX_DOCKERFILE_PATH:-Dockerfile}
      args:
        SERVICE_PORT: ${NGINX_PORT:-80}
        APP_ENV: ${APP_ENV:-development}
        APP_VERSION: ${APP_VERSION:-1.0.0}
    environment:
      - TZ=${TZ:-UTC}
      - NGINX_PORT=${NGINX_PORT:-80}
    ports:
      - "${NGINX_PORT:-80}:${NGINX_PORT:-80}"
    volumes:
      - nginx_www_data:/usr/share/nginx/html
      - nginx_logs:/var/log/nginx
      - nginx_conf:/etc/nginx/conf.d
    healthcheck:
      test: ${NGINX_HEALTHCHECK_CMD:-["CMD-SHELL", "curl -f http://localhost:${NGINX_PORT:-80}/health || exit 1"]}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-10s}
    restart: unless-stopped
    networks:
      - honeybun-network
      - fks-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  honeybun-network:
    driver: bridge
  fks-network:
    driver: bridge

volumes:
  nginx_www_data:
    driver: local
  nginx_logs:
    driver: local
  nginx_conf:
    driver: local